services:
    solid-pg-starter:
        image: ghcr.io/scrumdojo/dev-playwright:v4
        hostname: solid-pg-starter
        volumes:
            - devhome:/home/dev

    postgres:
        image: postgres:18
        hostname: postgres
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
            POSTGRES_DB: dev
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    devhome:
    db:
